### ISSUE TITLE
Refresh cached EFRuP conditions

### ISSUE THREAD

**Issue by Sandy-at-Tazama** [tazama-lf/event-flow#8]
**As a** Tazama system operator
**I want** event flow conditions cache to be up-to-date with what is stored in the database on start-up or on manual request
**so that** I can be assured that when retrieving conditions, they will always be found in cache

New functionality is being added to the Tazama system to be able to block or override a transaction event evaluation based on the evaluation of conditions against one of the transaction event attributes. The purpose of this user story is to provide a feature to allow a user to submit a request, to refresh cache from the database, with active or all conditions and edges, via an Admin API.  This feature should automatically be run on system startup.

See epic https://github.com/frmscoe/tazama-project/issues/12

#### Sequence diagram
```mermaid
sequenceDiagram
  participant admin as Admin
  participant tmsapi as Admin API
  participant cache as Cache
  participant DB as DB

  admin->>tmsapi: refreshCache()
  tmsapi->>cache: refreshCache()
  cache->>cache: emptyCache 
  cache->>DB: refreshCache()
  DB->>cache: updateConditions(activeConditionsOnly)
  cache->>tmsapi: 200Ok
  tmsapi->>admin: 200Ok
```

## Acceptance criteria
1. Add an environment variable for `ACTIVECONDITIONSONLY`
2. Create an Admin API that has access to the Tazama database
- recommended `/v1/admin/event-flow-control/cache`
3. Create a REST (PUT) endpoint to allow a user to refresh conditions in the Tazama graph cache
4. Add to coe-lib (only start once and not multiple times)
 - add to admin-service repo - https://github.com/frmscoe/admin-service/issues/45
 - add to coe-lib repo - https://github.com/frmscoe/frms-coe-lib/issues/157

## Functionality
1.  If  `ACTIVECONDITIONSONLY` = Y, then retrieve all active conditions and edges (`xprtnDtTm` < NOW) provided from the database and store in cache
2.  If  `ACTIVECONDITIONSONLY` = N, then retrieve **all** conditions and edges from the database and store in cache

## Complete Success Criteria
1. Empty cache
2. Retrieve all conditions based on the environment variable  `ACTIVECONDITIONSONLY`

**Success response**
200 OK

**Error responses**      
4xx
5xx

https://valkey.io/topics/persistence/

**Comment by cshezi** [comment]
**Research on Valkey's Data Persistence**



**Findings:**



Valkey has two methods for persisting data:



1. **AOF (Append Only File):** 
   - Records every write instruction and stores them in a backup file. This file can be executed at any time to recreate the dataset.



2. **RDB (Valkey Database):** 
   - Takes snapshots at specified intervals or when the data size reaches a specified limit. This snapshot reflects the data stored in memory.



Valkey utilizes multiple threads to handle data backup. The main thread is dedicated to processing incoming data and interacts only with RAM or temporary memory. A secondary thread/process is responsible for backing up the data and handling disk I/O operations, potentially using an SSD for increased persistence.



By default, Valkey saves snapshots of the dataset to disk in a binary file named `dump.rdb`.
The snapshot is taken every second (RDB)



**Conclusion:**



Both persistence strategies rely heavily on the write operations within the Valkey database. In our current use case, writes are triggered only by end-users adding conditions, meaning that the data backup rate is limited by human interaction speed. Thus, the AOF method is ideal in this context, as it aligns well with the expected workload.



Theoretically, any ongoing operation will impact system performance. Therefore, if a user adds a condition while the event flow rule reads data, we might observe performance degradation, as this is a system-driven process.

**Comment by Lenbkr** [comment]
Look into using distributed locks (redis/valkey docs) to prevent multiple resources from trying to refresh the cache on startup all at once.
